### ISSUE TITLE
Missing Tiles after successful run

### ISSUE THREAD

**Issue by BackpackinDan** [mantlik/osm2garmin#138]
Hi. I was able to run the osm2garmin successfully, however I seem to be missing a lot of elevation contours and/or tiles.  Has anyone had this issue?  I wanted a high level of topographic detail for the USA_west region so I set my minor and medium contour thresholds at 10000 and 20000 meters.  I also increased the maximum number of SRTM3 tiles in a single contours file to 10 and the maximum number of contours in a single 3x3 arc secs cell to 20.  My guess would be that I need to further increase the max number of SRTM3 tiles in a single contours file, but I don't have a lot of experience with the program.  Any help would be appreciated.  -BackpackinDan

![osm2garmin map](https://cloud.githubusercontent.com/assets/19897552/15995746/d46c6832-30d4-11e6-8610-bf701860abc7.JPG)
![osm2garmin options](https://cloud.githubusercontent.com/assets/19897552/15995752/e51a3bf0-30d4-11e6-8915-a873b42f21b2.JPG)

**Comment by mantlik** [comment]
Hi BackpackinDan,
My guess is that your problem is the "Maximum no. of contours in a single 3x3 cell". Try increase this value e.g. to 50. Don't forget to delete existing faulty contours files before running the application.
Hope this helps.

**Comment by BackpackinDan** [comment]
Thanks for the quick reply! Can I also increase the no. of SRTM3 tiles in a single contours file?  If I were to increase it, what would you suggest??  Maybe 20 or even 30?

**Comment by BackpackinDan** [comment]
So, I've tried running the program several different times with different options for how the contours are processed but I keep getting some patchy areas without any contours.  The areas without contour lines seem to be mostly at higher elevations where there are steep slopes, but not always.  I tried increasing the max no. of contours in a single 3x3 arc secs cell to 800 but that didn't solve the problem.

Any ideas? It seems like either I am missing SRTM source data or the data isn't getting processed correctly for some reason.  Is there another download source for the SRTM data?

-BackpackinDan

**Comment by berezhinskiy** [comment]
Hello,
The same issue with some areas without any contours. Attached map generated using following configuration:

srtm_step=5
contour_minor_interval=25
contour_medium_interval=50
contour_major_interval=100
plot_minor_threshold=10000
plot_medium_threshold=10000
contours_density=500

<img width="1155" alt="screen shot 2016-07-20 at 8 21 08 pm" src="https://cloud.githubusercontent.com/assets/502972/16995927/8c40be90-4eb7-11e6-8e7b-f790d0fcdf82.png">

**Comment by mantlik** [comment]
Hi, 
The problem is that SRTM data are sparse in some areas. Osm2Garmin contour creation routine does not interpolate over missing data, but does not generate contours for the cells with missing data at all. Minimum size of such area if just a single point is missing is approximately 200x200 meters, i.e. 2x2 SRTM cells.

**Comment by mantlik** [comment]
BackpackinDan, you are most probably facing the same problem as berezhinskiy - see my previous comment.

**Comment by berezhinskiy** [comment]
Hello, thanks for reply.
SRTM3 data is present for the same regions if I create it manually by mkgmap with SRTM3 data. Please, see attached screenshot. So, I assume that it is a bug. 
<img width="737" alt="screen shot 2016-07-21 at 10 36 06 am" src="https://cloud.githubusercontent.com/assets/502972/17014795/42d10e0e-4f2f-11e6-8b2c-8f82ba85bfea.png">

**Comment by mantlik** [comment]
Can you, please, provide geographic coordinates of the region on the screenshot?
